FROM golang:1.21 as builder

WORKDIR /app

COPY . .
RUN go install github.com/swaggo/swag/cmd/swag@latest
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -v -o main ./cmd/main
RUN CGO_ENABLED=0 swag init -g ./cmd/main/main.go -o cmd/main/docs

FROM scratch as production

WORKDIR /app

COPY --from=builder /app/main .
ENV GIN_MODE=release

EXPOSE 3000

CMD ["./main"]