FROM golang:1.21 as builder

WORKDIR /app

COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -v -o main ./cmd/main

FROM scratch as production

WORKDIR /app

COPY --from=builder /app/main .
ENV GIN_MODE=release

EXPOSE 3000

CMD ["./main"]