version: '3.8'

networks:
  kitkit:
    driver: bridge

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    container_name: postgres
    volumes:
      - ./tmp/database/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
    networks:
      - kitkit
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    extra_hosts:
      - host.docker.internal:host-gateway
  kitkit-back-go:
    build:
      context: .
      dockerfile: ./.docker/dockerfiles/Dockerfile
    entrypoint: ["sh", "./.docker/entrypoints/entrypoint-dev.sh"]
    # image: rafaelcava1/kitkit-back-go:v6
    container_name: kitkit-back-go
    restart: always
    environment:
      HOST: host.docker.internal
      PORT: 5432
      USER: postgres
      DB_NAME: postgres
      PASSWORD: postgres
      SECRET: 123456
    ports:
      - 3000:3000
    networks:
      - kitkit
    volumes:
      - .:/usr/kitkit-back-go/app
    extra_hosts:
      - host.docker.internal:host-gateway
    depends_on:
      - postgres